# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: getong/mariadb-action@v1.1
      with:
        host port: 3306
        container port: 3306
        character set server: "utf8"
        collation server: "utf8_general_ci"
        mariadb version: "latest"
        mysql database: "maria_test"
    - name: Build with Maven
      run: mvn -B package --file pom.xml
